app_url: APPLICATION_URL_HERE
app_name: APPLICATION_NAME_HERE
app_logo: logo.png
app_header_logo: logo.png
base_coin: ETH
app_coin: WETH
auto_approval: true
secret_key_base: SECRET_KEYBASE_HERE
ethereum_provider: https://ropsten.infura.io/v3/17def5988a254395a0570477c141050c
signer_private_key:  SIGNER_PRIVATE_KEY_HERE #Do not keep currencies to this address
coingecko_url: https://api.coingecko.com/api/v3/simple/price
contract_address:
  erc721: 'ERC_721_CONTRACT_ADDRESS_HERE'
gasstation_url: https://ethgasstation.info/api/ethgasAPI.json
etherscan:
  api_key: API_KEY_HERE
  api_url: https://api-rinkeby.etherscan.io/api
pinata:
  api_key: PINATA_API_KEY_HERE
  api_secret: PINATA_API_SECRET_HERE
  base_url: https://api.pinata.cloud/pinning/pinFileToIPFS
default_fees:
  service_fee: 2.5
discussion_url: DISCUSSION_URL_HERE
support_url: SUPPORT_URL_HERE
etherscan_url: https://rinkeby.etherscan.io
